import React from 'react';
import { AlertTriangle } from 'lucide-react';

const DISCLAIMER = "TradeSignal Pro is not registered with SEBI as an Investment Adviser or Research Analyst. Forecasts are generated by statistical models and are not financial advice. Past performance, including any displayed accuracy statistics, does not guarantee future results. You are responsible for your own trading decisions.";

export default function Disclaimer({ className = '' }) {
  return (
    <div className={`disclaimer flex items-start space-x-2 ${className}`}>
      <AlertTriangle className="w-3 h-3 text-amber-500 flex-shrink-0 mt-0.5" />
      <p>{DISCLAIMER}</p>
    </div>
  );
}
